FROM postgres:17.11-bookworm@sha256:051f7b7b3abdd564d5d1bd1e8c4b9c1b6e77087d1dd22020ede611c096a272e0

COPY scripts/private-db-bootstrap.sh /usr/local/bin/private-db-bootstrap
RUN chmod 0555 /usr/local/bin/private-db-bootstrap

ENTRYPOINT ["/usr/local/bin/private-db-bootstrap"]
